---
title: "Supplementary Figures"
output: html_notebook
---

# FIG S1: GRO vs PRO in Maize

```{r, fig.width=10, fig.height=4}

#### TSS

fill <- wes_palette("Cavalcanti1")

metagene            <- read.delim(file = "/home/NVME/Maize/Bo/metaplot/Bo_maize_TSS")
colnames(metagene)  <- c("axis", "coverage", "Pro (+)", "Pro (-)")

dim(metagene)
metageneplot <- matrix(0, ncol = 3 , nrow = dim(metagene)[1]*2)
metageneplot <- as.data.frame(metageneplot)
colnames(metageneplot)    <- c("Distance from TSS (5'end)","Normalized reads", "Strand")

reads    <- c(metagene$`Pro (+)`, metagene$`Pro (-)`)
distance <- c(metagene$axis, metagene$axis) 
strand   <- c(rep(x = "Pro(-)", dim(metagene)[1]), rep(x = "Pro(+)", dim(metagene)[1]))

metageneplot[,1] <- as.integer(distance) * -1 
metageneplot[,2] <- as.numeric(reads)
metageneplot[,3] <- strand

TSS.maize_BO <- ggplot() + geom_line(aes(y = `Normalized reads`, x =  `Distance from TSS (5'end)`, colour = Strand), size=1,
                           data = metageneplot, stat="identity") +
  theme(legend.position="bottom", legend.direction="horizontal",
        legend.title = element_blank()) +
  #xlab("") +
  ylab("") +
  xlim(-1000, 1000) +
  ggtitle("Maize PRO-seq read") +
  scale_color_manual(values=c(fill[4], fill[5])) +
  theme(axis.line.x = element_line(size=1, colour = "black"),
        axis.line.y = element_line(size=1, colour = "black"),
        panel.grid.major = element_line(colour = "#d3d3d3"), panel.grid.minor = element_blank(),
        panel.border = element_blank(), panel.background = element_blank()) +
  theme(plot.title = element_text(size = 14, family = "Tahoma", face = "bold"),
        text=element_text(family="Tahoma"),
        axis.text.x=element_text(colour="black", size = 10),
        axis.text.y=element_text(colour="black", size = 10),
        legend.key=element_rect(fill="white", colour="white"))


metagene            <- read.delim(file = "/home/NVME/Pro-seq/Second/Metagene/Maize/maize_tss.txt")
colnames(metagene)  <- c("axis", "coverage", "Pro (+)", "Pro (-)")

dim(metagene)
metageneplot <- matrix(0, ncol = 3 , nrow = dim(metagene)[1]*2)
metageneplot <- as.data.frame(metageneplot)
colnames(metageneplot)    <- c("Distance from TSS (5'end)","Normalized reads", "Strand")

reads    <- c(metagene$`Pro (+)`, metagene$`Pro (-)`)
distance <- c(metagene$axis, metagene$axis) 
strand   <- c(rep(x = "Pro(+)", dim(metagene)[1]), rep(x = "Pro(-)", dim(metagene)[1]))

metageneplot[,1] <- as.integer(distance) * -1 
metageneplot[,2] <- as.numeric(reads)
metageneplot[,3] <- strand

TSS.maize_GRO <- ggplot() + geom_line(aes(y = `Normalized reads`, x =  `Distance from TSS (5'end)`, colour = Strand), size=1,
                           data = metageneplot, stat="identity") +
  theme(legend.position="bottom", legend.direction="horizontal",
        legend.title = element_blank()) +
  #xlab("") +
  xlim(-1000, 1000) +
  ggtitle("Maize GRO-seq read") +
  scale_color_manual(values=c(fill[4], fill[5])) +
  theme(axis.line.x = element_line(size=1, colour = "black"),
        axis.line.y = element_line(size=1, colour = "black"),
        panel.grid.major = element_line(colour = "#d3d3d3"), panel.grid.minor = element_blank(),
        panel.border = element_blank(), panel.background = element_blank()) +
  theme(plot.title = element_text(size = 14, family = "Tahoma", face = "bold"),
        text=element_text(family="Tahoma"),
        axis.text.x=element_text(colour="black", size = 10),
        axis.text.y=element_text(colour="black", size = 10),
        legend.key=element_rect(fill="white", colour="white"))

FIGS1 <- TSS.maize_GRO + TSS.maize_BO  + plot_layout(ncol = 2)
FIGS1

ggsave("/home/NVME/FIGS1", plot= FIGS1, device = "jpg", scale = 1, width = 10, height = 4, units = c("in"),dpi = 850, limitsize = TRUE)

```


# FIG S2: Pausing Index 

```{r}


metagene  <- read.delim(file = "/home/NVME/Pro-seq/Second/Pausing_index/results") %>%
  filter(PI < 10 & PI >=0)


set1 <- metagene %>%
  filter(PI < 2 & PI >=0)%>%
  mutate(SET = 1) %>%
  select(Gene, SET, Expression, GeneLength, nexons)

set2 <- metagene %>%
  filter(PI < 4 & PI >=2)%>%
   mutate(SET = 2) %>%
    select(Gene, SET, Expression, GeneLength, nexons)

set3 <- metagene %>%
  filter(PI < 6 & PI >=4)%>%
  mutate(SET = 3) %>%
  select(Gene, SET, Expression, GeneLength, nexons)

set4 <- metagene %>%
  filter(PI < 8 & PI >=6)%>%
  mutate(SET = 4) %>%
  select(Gene, SET, Expression, GeneLength, nexons)

set5 <- metagene %>%
  filter(PI < 10 & PI >=8)%>%
  mutate(SET = 5) %>%
  select(Gene, SET, Expression, GeneLength, nexons)

write.table(set1$Gene, file = "/home/NVME/Pro-seq/Second/Pausing_index/set1",col.names = F,  quote = F, sep = "\t",row.names = F)
write.table(set2$Gene, file = "/home/NVME/Pro-seq/Second/Pausing_index/set2",col.names = F,  quote = F, sep = "\t",row.names = F)
write.table(set3$Gene, file = "/home/NVME/Pro-seq/Second/Pausing_index/set3",col.names = F,  quote = F, sep = "\t",row.names = F)
write.table(set4$Gene, file = "/home/NVME/Pro-seq/Second/Pausing_index/set4",col.names = F,  quote = F, sep = "\t",row.names = F)
write.table(set5$Gene, file = "/home/NVME/Pro-seq/Second/Pausing_index/set5",col.names = F,  quote = F, sep = "\t",row.names = F)

newset <- rbind(set1,set2,set3,set4,set5)

kolor <- wes_palette(name = "Cavalcanti1")

p <- ggplot(newset, aes(as.factor(SET), Expression))
p + geom_boxplot(aes(fill = SET)) 


GL <- ggplot(newset, aes(as.factor(SET), GeneLength))
GL + geom_boxplot(aes(fill = SET)) + ylim(0,7500) 

GL <- ggplot(newset, aes(as.factor(SET), GeneLength)) +
  geom_boxplot(aes(fill = as.factor(SET)))  + labs( x="Pausing Index groups") +  theme_bw() +
  scale_fill_manual(values = kolor) +
  ylim(0,7500) +
  theme(plot.title=element_text(colour = "navyblue",face ="bold", size= 18, margin = margin(t=20, b=20)),
        strip.text.x=element_text(size=14, face = "bold"),
        strip.background=element_rect(colour="black", fill=kolor[2]),
        axis.title.y=element_text(margin=margin(0,20,0,0)),
        axis.text=element_text(size=14), 
        axis.title=element_text(size=14,face="bold"),
        axis.title.x=element_text(margin=margin(20,0,0,0))) 

Ex <- ggplot(newset, aes(as.factor(SET), Expression)) +
  geom_boxplot(aes(fill = as.factor(SET)))  + labs( x="Pausing Index groups") +  theme_bw() +
  scale_fill_manual(values = kolor) +
  ylim(0,500) +
  theme(plot.title=element_text(colour = "navyblue",face ="bold", size= 18, margin = margin(t=20, b=20)),
        strip.text.x=element_text(size=14, face = "bold"),
        strip.background=element_rect(colour="black", fill=kolor[2]),
        axis.title.y=element_text(margin=margin(0,20,0,0)),
        axis.text=element_text(size=14), 
        axis.title=element_text(size=14,face="bold"),
        axis.title.x=element_text(margin=margin(20,0,0,0))) 


Ne <- ggplot(newset, aes(as.factor(SET), nexons)) +
  geom_boxplot(aes(fill = as.factor(SET)))  + labs( x="Pausing Index groups") +  theme_bw() +
  scale_fill_manual(values = kolor) +
  ylim(0,15) +
  theme(plot.title=element_text(colour = "navyblue",face ="bold", size= 18, margin = margin(t=20, b=20)),
        strip.text.x=element_text(size=14, face = "bold"),
        strip.background=element_rect(colour="black", fill=kolor[2]),
        axis.title.y=element_text(margin=margin(0,20,0,0)),
        axis.text=element_text(size=14), 
        axis.title=element_text(size=14,face="bold"),
        axis.title.x=element_text(margin=margin(20,0,0,0))) 


ggsave("/home/NVME/FigGL.jpg", plot= GL, device = "jpg", scale = 1, width = 5, height = 4, units = c("in"),dpi = 450, limitsize = TRUE)
ggsave("/home/NVME/FigEx.jpg", plot= Ex, device = "jpg", scale = 1, width = 5, height = 4, units = c("in"),dpi = 450, limitsize = TRUE)
ggsave("/home/NVME/FigNe.jpg", plot= Ne, device = "jpg", scale = 1, width = 5, height = 4, units = c("in"),dpi = 450, limitsize = TRUE)

```


```{r, fig.height= 4, fig.width=14}

metagene            <- read.delim(file = "/home/NVME/Pro-seq/Second/Metagene/set5.txt") # change this for every set
colnames(metagene)  <- c("axis", "coverage", "Pro (+)", "Pro (-)")

dim(metagene)
metageneplot <- matrix(0, ncol = 3 , nrow = dim(metagene)[1]*2)
metageneplot <- as.data.frame(metageneplot)
colnames(metageneplot)    <- c("Distance from TSS (5'end)","Normalized reads", "Strand")

reads    <- c(metagene$`Pro (+)`, metagene$`Pro (-)`)
distance <- c(metagene$axis, metagene$axis) 
strand   <- c(rep(x = "Pro(-)", dim(metagene)[1]), rep(x = "Pro(+)", dim(metagene)[1]))

metageneplot[,1] <- as.integer(distance) * -1 
metageneplot[,2] <- as.numeric(reads)
metageneplot[,3] <- strand

#metageneplot[which(metageneplot$Strand=="Pro(-)"), 2]   <- metageneplot[which(metageneplot$Strand=="Pro(-)"), 2]* -1


color <- wes_palette("Cavalcanti1")
fill <- c(color[2], color[1])

# Run this for the 5 sets changing p1 p2 p3... using the different sets above

p5 <- ggplot() + geom_line(aes(y = `Normalized reads`, x =  `Distance from TSS (5'end)`, colour = Strand), size=1.3,
                           data = metageneplot, stat="identity") +
  theme(legend.position="bottom", legend.direction="horizontal",
        legend.title = element_blank()) +
  ylim(0,0.3) +
  labs(x="Distance from Enhancer candidates center") +
  #ggtitle("Metaplot of nascent RNA in intergenic regions") +
  scale_color_manual(values=fill) +
  theme(axis.line.x = element_line(size=1, colour = "black"),
        axis.line.y = element_line(size=1, colour = "black"),
        panel.grid.major = element_line(colour = "#d3d3d3"), panel.grid.minor = element_blank(),
        panel.border = element_blank(), panel.background = element_blank()) +
  theme(plot.title = element_text(size = 14, family = "Tahoma", face = "bold"),
        text=element_text(family="Tahoma"),
        axis.text.x=element_text(colour="black", size = 10),
        axis.text.y=element_text(colour="black", size = 10),
        legend.key=element_rect(fill="white", colour="white")) +
  scale_x_continuous(breaks =c(-2000,-1000,0,1000,2000), labels = c("-2kb", "-1kb", "0", "+1kb", "+2kb")) +
  geom_hline(yintercept = 0)



ggsave("/home/NVME/FigSupPI.jpg", plot= Graph, device = "jpg", scale = 1, width = 14, height = 4, units = c("in"),dpi = 850, limitsize = TRUE)
Graph <- p1 +p2 +p3 +p4 + p5 + plot_layout(ncol = 5)
Graph

```

#FIG S3: Bidirectional Subset of promoters showing bi-directional transcription

```{r}

metagene            <- read.delim(file = "/home/NVME/Pro-seq/Second/Metagene/Bidirection")
colnames(metagene)  <- c("axis", "coverage", "Pro (+)", "Pro (-)")

dim(metagene)
metageneplot <- matrix(0, ncol = 3 , nrow = dim(metagene)[1]*2)
metageneplot <- as.data.frame(metageneplot)
colnames(metageneplot)    <- c("Distance from TSS (5'end)","Normalized reads", "Strand")

reads    <- c(metagene$`Pro (+)`, metagene$`Pro (-)`)
distance <- c(metagene$axis, metagene$axis) 
strand   <- c(rep(x = "Pro(-)", dim(metagene)[1]), rep(x = "Pro(+)", dim(metagene)[1]))

metageneplot[,1] <- as.integer(distance) * -1 
metageneplot[,2] <- as.numeric(reads)
metageneplot[,3] <- strand

color <- wes_palette("Cavalcanti1")
fill <- c(color[4], color[5])

bi <- ggplot() + geom_line(aes(y = `Normalized reads`, x =  `Distance from TSS (5'end)`, colour = Strand), size=1.3,
                           data = metageneplot, stat="identity") +
  theme(legend.position="bottom", legend.direction="horizontal",
        legend.title = element_blank()) +
  #scale_x_continuous(breaks=seq(2006,2014,1)) +
  #labs(x="Year", y="USD million") +
  ylim(0, 0.25)+
  ggtitle("Bidirectional Transcription in a subset of Cassava genes") +
  scale_color_manual(values=fill) +
  theme(axis.line.x = element_line(size=1, colour = "black"),
        axis.line.y = element_line(size=1, colour = "black"),
        panel.grid.major = element_line(colour = "#d3d3d3"), panel.grid.minor = element_blank(),
        panel.border = element_blank(), panel.background = element_blank()) +
  theme(plot.title = element_text(size = 12, family = "Tahoma", face = "bold"),
        text=element_text(family="Tahoma"),
        axis.text.x=element_text(colour="black", size = 10),
        axis.text.y=element_text(colour="black", size = 10),
        legend.key=element_rect(fill="white", colour="white"))

ggsave("/home/NVME/FigS3.jpg", plot= bi, device = "jpg", scale = 1, width = 6, height = 4, units = c("in"),dpi = 850, limitsize = TRUE)

bi
```

#FIG S4: Pro-seq peaks identified in intergenic regions

```{r}

metagene            <- read.delim(file = "/home/NVME/Pro-seq/Second/Metagene/white/NCDREG.txt")
colnames(metagene)  <- c("axis", "coverage", "Pro (+)", "Pro (-)")

dim(metagene)
metageneplot <- matrix(0, ncol = 3 , nrow = dim(metagene)[1]*2)
metageneplot <- as.data.frame(metageneplot)
colnames(metageneplot)    <- c("Distance from TSS (5'end)","Normalized reads", "Strand")

reads    <- c(metagene$`Pro (+)`, metagene$`Pro (-)`)
distance <- c(metagene$axis, metagene$axis) 
strand   <- c(rep(x = "Pro(+)", dim(metagene)[1]), rep(x = "Pro(-)", dim(metagene)[1]))

metageneplot[,1] <- as.integer(distance) * -1 
metageneplot[,2] <- as.numeric(reads)
metageneplot[,3] <- strand

color <- wes_palette("Zissou1")
fill <- c(color[1], color[4])

IGe <- ggplot() + geom_line(aes(y = `Normalized reads`, x =  `Distance from TSS (5'end)`, colour = Strand), size=1.3,
                           data = metageneplot, stat="identity") +
  theme(legend.position="bottom", legend.direction="horizontal",
        legend.title = element_blank()) +
  labs(x="Distance from Intergenic Peak") +
  ggtitle("Cassava nascent RNA in intergenic regions") +
  scale_color_manual(values=fill) +
  theme(axis.line.x = element_line(size=1, colour = "black"),
        axis.line.y = element_line(size=1, colour = "black"),
        panel.grid.major = element_line(colour = "#d3d3d3"), panel.grid.minor = element_blank(),
        panel.border = element_blank(), panel.background = element_blank()) +
  theme(plot.title = element_text(size = 14, family = "Tahoma", face = "bold"),
        text=element_text(family="Tahoma"),
        axis.text.x=element_text(colour="black", size = 10),
        axis.text.y=element_text(colour="black", size = 10),
        legend.key=element_rect(fill="white", colour="white"))

IGe

ggsave("/home/NVME/FigS4.jpg", plot= IGe, device = "jpg", scale = 1, width = 6, height = 4, units = c("in"),dpi = 850, limitsize = TRUE)


```


#FIG S5: Maize Correspondence between GRO and PRO 

```{r}

metagene            <- read.delim(file = "/home/NVME/Pro-seq/Second/Metagene/Maize/maize_enhancers_bo.txt")
colnames(metagene)  <- c("axis", "coverage", "Pro (+)", "Pro (-)")

dim(metagene)
metageneplot <- matrix(0, ncol = 3 , nrow = dim(metagene)[1]*2)
metageneplot <- as.data.frame(metageneplot)
colnames(metageneplot)    <- c("Distance from TSS (5'end)","Normalized reads", "Strand")

reads    <- c(metagene$`Pro (+)`, metagene$`Pro (-)`)
distance <- c(metagene$axis, metagene$axis) 
strand   <- c(rep(x = "Pro(+)", dim(metagene)[1]), rep(x = "Pro(-)", dim(metagene)[1]))

metageneplot[,1] <- as.integer(distance) * -1 
metageneplot[,2] <- as.numeric(reads)
metageneplot[,3] <- strand

color <- wes_palette("Moonrise1")
fill <- c(color[3], color[4])

PROGRO <- ggplot() + geom_line(aes(y = `Normalized reads`, x =  `Distance from TSS (5'end)`, colour = Strand), size=1.3,
                           data = metageneplot, stat="identity") +
  theme(legend.position="bottom", legend.direction="horizontal",
        legend.title = element_blank()) +
  labs(x="Distance from Intergenic Peak") +
  ggtitle("PRO-seq reads mapped to dREG regions identified with GRO-seq") +
  scale_color_manual(values=fill) +
  theme(axis.line.x = element_line(size=1, colour = "black"),
        axis.line.y = element_line(size=1, colour = "black"),
        panel.grid.major = element_line(colour = "#d3d3d3"), panel.grid.minor = element_blank(),
        panel.border = element_blank(), panel.background = element_blank()) +
  theme(plot.title = element_text(size = 11, family = "Tahoma", face = "bold"),
        text=element_text(family="Tahoma"),
        axis.text.x=element_text(colour="black", size = 10),
        axis.text.y=element_text(colour="black", size = 10),
        legend.key=element_rect(fill="white", colour="white"))

PROGRO

ggsave("/home/NVME/FigS5.jpg", plot= PROGRO, device = "jpg", scale = 1, width = 7, height = 4, units = c("in"),dpi = 850, limitsize = TRUE)

```



# FIG S6 Arabidopsis Candidates



```{r, fig.height=4, fig.width=8.5}

metagene            <- read.delim(file = "/home/DB/proseq/Arabidopsis/dREG/Enhancers_Ara_GRO.txt")
colnames(metagene)  <- c("axis", "coverage", "Pro (+)", "Pro (-)")

dim(metagene)
metageneplot <- matrix(0, ncol = 3 , nrow = dim(metagene)[1]*2)
metageneplot <- as.data.frame(metageneplot)
colnames(metageneplot)    <- c("Distance from TSS (5'end)","Normalized reads", "Strand")

reads    <- c(metagene$`Pro (-)`, metagene$`Pro (+)`)
distance <- c(metagene$axis, metagene$axis) 
strand   <- c(rep(x = "Pro(-)", dim(metagene)[1]), rep(x = "Pro(+)", dim(metagene)[1]))

metageneplot[,1] <- as.integer(distance) * 1 
metageneplot[,2] <- as.numeric(reads)
metageneplot[,3] <- strand

metageneplot[which(metageneplot$Strand=="Pro(-)"), 2]   <- metageneplot[which(metageneplot$Strand=="Pro(-)"), 2]* -1

color <- wes_palette("Cavalcanti1")
fill <- c(color[3], color[4])

p1 <- ggplot() + geom_line(aes(y = `Normalized reads`, x =  `Distance from TSS (5'end)`, colour = Strand), size=1.3,
                           data = metageneplot, stat="identity") +
  theme(legend.position="bottom", legend.direction="horizontal",
        legend.title = element_blank()) +
  labs(x="Distance from Enhancer candidates center") +
  ggtitle("Transcription at Arabidopsis candidates (Bo Zhu et. al, n = 5,870)") +
  scale_color_manual(values=fill) +
  theme(axis.line.x = element_line(size=1, colour = "black"),
        axis.line.y = element_line(size=1, colour = "black"),
        panel.grid.major = element_line(colour = "#d3d3d3"), panel.grid.minor = element_blank(),
        panel.border = element_blank(), panel.background = element_blank()) +
  theme(plot.title = element_text(size = 14, family = "Tahoma", face = "bold"),
        text=element_text(family="Tahoma"),
        axis.text.x=element_text(colour="black", size = 10),
        axis.text.y=element_text(colour="black", size = 10),
        legend.key=element_rect(fill="white", colour="white")) +
  scale_x_continuous(breaks =c(-4000,-2000,-1000,0,1000,2000,4000), labels = c("-4kb", "-2kb", "-1kb", "0", "+1kb", "+2kb", "+4kb")) +
  geom_hline(yintercept = 0)

p1


```

```{r, fig.height=4, fig.width=8.5}

metagene            <- read.delim(file = "/home/DB/proseq/Arabidopsis/dREG/Enhancers_Ara_3k.txt")
colnames(metagene)  <- c("axis", "coverage", "Pro (+)", "Pro (-)")

dim(metagene)
metageneplot <- matrix(0, ncol = 3 , nrow = dim(metagene)[1]*2)
metageneplot <- as.data.frame(metageneplot)
colnames(metageneplot)    <- c("Distance from TSS (5'end)","Normalized reads", "Strand")

reads    <- c(metagene$`Pro (-)`, metagene$`Pro (+)`)
distance <- c(metagene$axis, metagene$axis) 
strand   <- c(rep(x = "Pro(-)", dim(metagene)[1]), rep(x = "Pro(+)", dim(metagene)[1]))

metageneplot[,1] <- as.integer(distance) * 1 
metageneplot[,2] <- as.numeric(reads)
metageneplot[,3] <- strand

metageneplot[which(metageneplot$Strand=="Pro(-)"), 2]   <- metageneplot[which(metageneplot$Strand=="Pro(-)"), 2]* -1

color <- wes_palette("Cavalcanti1")
fill <- c(color[3], color[4])

p1 <- ggplot() + geom_line(aes(y = `Normalized reads`, x =  `Distance from TSS (5'end)`, colour = Strand), size=1.3,
                           data = metageneplot, stat="identity") +
  theme(legend.position="bottom", legend.direction="horizontal",
        legend.title = element_blank()) +
  labs(x="Distance from Enhancer candidates center") +
  ylim(-0.05, 0.05) +
  ggtitle("Arabidopsis candidates at least 3k from the nearest gene (n = 573)") +
  scale_color_manual(values=fill) +
  theme(axis.line.x = element_line(size=1, colour = "black"),
        axis.line.y = element_line(size=1, colour = "black"),
        panel.grid.major = element_line(colour = "#d3d3d3"), panel.grid.minor = element_blank(),
        panel.border = element_blank(), panel.background = element_blank()) +
  theme(plot.title = element_text(size = 14, family = "Tahoma", face = "bold"),
        text=element_text(family="Tahoma"),
        axis.text.x=element_text(colour="black", size = 10),
        axis.text.y=element_text(colour="black", size = 10),
        legend.key=element_rect(fill="white", colour="white")) +
  scale_x_continuous(breaks =c(-4000,-2000,-1000,0,1000,2000,4000), labels = c("-4kb", "-2kb", "-1kb", "0", "+1kb", "+2kb", "+4kb")) +
  geom_hline(yintercept = 0)

p1


```




